Hometask 03
LucasKruschewsky/lucas-react-mentoring pull request #2
Opened 2022-02-23 16:53 UTC by LucasKruschewsky

Some projects defaults, homepage style done

2022-02-25 16:16 UTC, eduardo-neto-epam requested changes
Excellent styling skills! &#128640; 
Please feel free to remove the Test component, since it is cluttering your app.
Take special attention to optimising your components removing function definitions and variable declarations from the component when possible.
Alternative is to memoize your functions, although tends to be overkill for small functions.
Reason being, every time the component renders, it will declare the functions and variable over and over again. 
Attention to the use of event listeners on useEffects, never forget the clean up function.

2022-02-25 16:16 UTC, eduardo-neto-epam commented on src/App.js
> +import Homepage from '@/Pages/Homepage';
@/pages not @/Pages

2022-02-25 16:16 UTC, eduardo-neto-epam commented on src/components/ErrorBoundary/styles.js
> +const ErroOuterContainer = styled(AppContainer)`
I believe there is a spelling here. Should be ErrorOuterContainer not ErroOuterContainer.
Please make sure the spelling os fixed everywhere ErrorOuterContainer is used.

2022-02-25 16:16 UTC, eduardo-neto-epam commented on src/components/MovieCard/index.jsx
> +      <img src={movie.image} alt={`${movie.name} banner`} />
I would destructure movie to avoid repetition. 
example: const { image, name, genre, year } = movie;

2022-02-25 16:16 UTC, eduardo-neto-epam commented on src/components/MovieList/index.jsx
> +  // Mocked data
Remove mockdata into its own file

2022-02-25 16:16 UTC, eduardo-neto-epam commented on src/components/MovieList/index.jsx
> +  const showGenreFilters = genreFilterList.map((item) => (
Optimize by extracting variables showGenreFilters, showMovies and numberOfMoviesFound out of the MovieList component.

2022-02-25 16:16 UTC, eduardo-neto-epam commented on src/components/Navbar/index.jsx
> +import _ from 'lodash';
avoid importing entire library to only use a few methods.
Consider using import { throttle } from 'lodash';

2022-02-25 16:16 UTC, eduardo-neto-epam commented on src/components/Navbar/index.jsx
> +  };
When ever possible extract variables and function from inside components.

2022-02-25 16:16 UTC, eduardo-neto-epam commented on src/components/Navbar/index.jsx
> +    window.addEventListener('scroll', _.throttle(handleNavbarBackground, 150));
When adding event listeners in a useEffect you should always return a clean up function to remove the event listener.

2022-03-01 16:00 UTC, LucasKruschewsky commented
Changes requested here will be merged on [typescript-migration pull request](https://github.com/LucasKruschewsky/lucas-react-mentoring/pull/3).

2022-03-01 16:00 UTC, closed without merging